# Generated by Django 3.2.8 on 2023-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_reading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_reading_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='semester',
            field=models.CharField(choices=[('Live', 'Live'), ('Delay', 'Delay'), ('Offline', 'Offline'), ('NAT', 'NAT'), ('Disabled', 'Disabled')], default='NAT', max_length=20),
        ),
    ]
