# Generated by Django 3.2.8 on 2023-03-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0002_auto_20230320_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='semester',
            new_name='status',
        ),
    ]
