# Generated by Django 3.2.8 on 2023-04-03 10:25

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0003_rename_semester_site_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='last_reading_at',
            new_name='last_reading_received_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.AddField(
            model_name='site',
            name='device_config',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='sit_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_lattitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='tpro_prefix',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='tpro_prefix'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.CharField(default='system/server', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_updated_by',
            field=models.CharField(default='system/server', max_length=100),
        ),
    ]
