# Generated by Django 3.2.8 on 2023-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0004_auto_20230403_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
