# Generated by Django 3.2.8 on 2023-04-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0005_auto_20230403_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='state',
            new_name='location',
        ),
    ]
