# Generated by Django 3.2.8 on 2023-04-03 15:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0008_site_tpro_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='total_params',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
