# Generated by Django 3.2.8 on 2023-04-04 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0009_site_total_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_master',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Project Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhp_app.project_master', verbose_name='project'),
        ),
    ]
