# Generated by Django 3.2.8 on 2023-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0010_auto_20230404_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_master',
            name='described_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Project Described Name'),
        ),
    ]
