# Generated by Django 3.2.8 on 2023-04-04 06:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0011_project_master_described_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='readings_2023',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('readings', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhp_app.site', verbose_name='site_id')),
            ],
            options={
                'unique_together': {('site_id', 'timestamp')},
            },
        ),
    ]
