# Generated by Django 3.2.8 on 2023-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhp_app', '0013_alter_site_last_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='last_reading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
